model = "gpt-5.5"
model_reasoning_effort = "xhigh"
web_search = "cached"
personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"

[sandbox_workspace_write]
network_access = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
gpt-5-codex = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[projects."/Users/paul/Projects/gremllm"]
trust_level = "trusted"

[projects."/Users/paul/Library/CloudStorage/GoogleDrive-paul@quantisan.com/My Drive/Data Guild/Mass Witness/research_poc_components"]
trust_level = "trusted"

[projects."/Users/paul/Projects/nexus"]
trust_level = "trusted"

[projects."/Users/paul/Projects/dotfiles"]
trust_level = "trusted"

[projects."/Users/paul/Projects/delphi"]
trust_level = "trusted"

[projects."/Users/paul/Projects/wri/planning"]
trust_level = "trusted"

[projects."/Users/paul/Library/CloudStorage/GoogleDrive-paul@quantisan.com/.shortcut-targets-by-id/1OZrt_MCsAOdkYArY9n2CDwTy1uWLDdWy/AI Collab/Calls"]
trust_level = "trusted"

[projects."/Users/paul/Projects/nagato"]
trust_level = "trusted"

[projects."/Users/paul/Projects/superpowers"]
trust_level = "trusted"

[projects."/Users/paul/Library/CloudStorage/GoogleDrive-paul@quantisan.com/My Drive/Quantisan LLC/meeting minutes"]
trust_level = "trusted"

[projects."/Users/paul/Projects/moonshine"]
trust_level = "trusted"

[tui]
experimental_mode = "plan"
status_line = ["model-with-reasoning", "context-remaining", "five-hour-limit", "weekly-limit"]

[mcp_servers.atlassianRovo]
url = "https://mcp.atlassian.com/v1/mcp"
