#!/usr/bin/env python3
"""Render an artifact root's lineage map from `Builds on:` edges.

Usage: build-lineage-map.py <artifact-root> [excluded-subfolder ...]

The edges live in each artifact's header (one canonical, upstream-only line);
this is the rendered view of them. Run it after saving, renaming, or moving an
artifact. It overwrites only the <!-- lineage:auto --> block in the artifact
root's README.md and leaves the hand-written README untouched.

Paths in a `Builds on:` line are relative to the artifact root (bare slug =
a root-level file, `<subfolder>/...` = a file under that subfolder). Excluded
subfolders (e.g. a throwaway bets/) are skipped when scanning for edges.
stdlib only; no dependencies.
"""

import re
import sys
from pathlib import Path

BEGIN, END = "<!-- lineage:auto -->", "<!-- /lineage:auto -->"

# `- Builds on: `a.md`, `problems/b.md``  → capture every backticked path.
EDGE_LINE = re.compile(r"^\s*[-*]?\s*Builds on:\s*(.+)$", re.IGNORECASE)
BACKTICKED = re.compile(r"`([^`]+)`")


def parse_edges(root, excluded):
    """child rel-path -> [parent rel-path, ...], in declaration order."""
    edges = {}
    for md in sorted(root.rglob("*.md")):
        rel = md.relative_to(root)
        if md.name == "README.md" or excluded & set(rel.parts[:-1]):
            continue
        for line in md.read_text(encoding="utf-8").splitlines():
            m = EDGE_LINE.match(line)
            if not m:
                continue
            parents = []
            for token in BACKTICKED.findall(m.group(1)):
                # keep the path only — drop any trailing "§section" or note
                parents.append(token.split()[0].split("§")[0].strip())
            if parents:
                edges.setdefault(rel.as_posix(), []).extend(parents)
    return edges


def rank(node, edges, memo, stack=frozenset()):
    """Longest path from node up to a root — used to order most-downstream first."""
    if node in memo:
        return memo[node]
    if node in stack:  # cycle guard
        return 0
    parents = edges.get(node, [])
    r = 0 if not parents else 1 + max(
        rank(p, edges, memo, stack | {node}) for p in parents
    )
    memo[node] = r
    return r


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: build-lineage-map.py <artifact-root> [excluded-subfolder ...]")
    root = Path(sys.argv[1]).resolve()
    if not root.is_dir():
        sys.exit(f"artifact root not found: {root}")
    excluded = {e.strip("/") for e in sys.argv[2:]}
    readme = root / "README.md"

    edges = parse_edges(root, excluded)
    children = set(edges)
    all_parents = {p for ps in edges.values() for p in ps}
    missing = sorted(p for p in all_parents if not (root / p).exists())

    # Most-downstream first; each node printed once with its direct parents.
    memo = {}
    ordered = sorted(children, key=lambda n: (-rank(n, edges, memo), n))

    lines = ["", "_Generated by the `strategic-artifact` skill's `build-lineage-map.py`"
             " from the `Builds on:` lines in each artifact — do not hand-edit._", ""]
    if not ordered:
        lines.append("_No `Builds on:` edges found yet._")
    for node in ordered:
        parents = ", ".join(f"`{p}`" for p in edges[node])
        lines.append(f"- `{node}`")
        lines.append(f"  ← {parents}")
    linked = children | all_parents
    lines.append("")
    lines.append(f"_{len(linked)} artifact(s) linked across {len(edges)} edge-set(s)."
                 " A node cited as a parent by several lines is a convergence point."
                 " Unlinked files carry no `Builds on:` line yet._")
    if missing:
        lines.append("")
        lines.append("**⚠ dead edges (path not found):**")
        lines.extend(f"- `{p}`" for p in missing)

    block = f"{BEGIN}\n" + "\n".join(lines).rstrip() + f"\n{END}"
    text = readme.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit(f"markers {BEGIN} / {END} not found in {readme}")
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.DOTALL)
    readme.write_text(new, encoding="utf-8")
    print(f"map rebuilt: {len(ordered)} node(s) with edges, {len(linked)} linked, "
          f"{len(missing)} dead edge(s)")
    if missing:
        print("dead edges:", ", ".join(missing))


if __name__ == "__main__":
    main()
